### ISSUE TITLE
Specify the position

### ISSUE THREAD

**Issue by CristianSarac** [szaboa/AchievementView#1]
Is there a way to specify the position of the view, down /up/middle ?
Where can you change the distance on where the view should appear ? For example at 50dp from bottom or something like that

**Comment by szaboa** [comment]
Hi @CristianSarac,
You need to specify the position relatively in your root layout. You could  use `RelativeLayout` or `FrameLayout` as the root view group, so you can have the `AchievementView` above your content with any margin from the bottom of the screen (see activity_main.xml).

Hope this answered your question.
