### ISSUE TITLE
Lower Android API version support

### ISSUE THREAD

**Issue by gchristov** [szaboa/AchievementView#2]
Is there a reason why the library only supports API >= 21? I have an app with API version 19 and I cannot use the library because of this :(

**Comment by szaboa** [comment]
Hello. I need to check what exactly requires min sdk 21, I will get back to you later today.

**Comment by gchristov** [comment]
Great, thank you!

**Comment by gchristov** [comment]
Did a bit of investigation on this myself (I really like the library haha)

Looks like the only thing that needs api 21 is the `ViewAnimationUtils.createCircularReveal()` call. Fortunately, there's a library that makes this possible on api <21:

https://github.com/ozodrukh/CircularReveal

I was able to get your sample app to work with this with the following changes:

1. In AchievementView.jt replace `ViewAnimationUtils.createCircularReveal` with `io.codetail.animation.ViewAnimationUtils.createCircularReveal`
2. In layout_achievement_view.xml wrap `achievement_left_layout` in `io.codetail.widget.RevealFrameLayout`

Sample app works exactly the same on api 19 now :)

![May-17-2019 11-08-31](https://user-images.githubusercontent.com/7644787/57920949-27d0d080-7894-11e9-9482-aa25cdc3520a.gif)

**Comment by szaboa** [comment]
Nice 👍 
Would you like to bake this into the library? Or you are going to use this modified version as a module in your application?

Btw, if you are working on a new application, I would say it's not worth to support Android 4.4 as you will have other difficulties like this.

**Comment by gchristov** [comment]
I agree but Android 4.4 (api 19) still has a relatively large (6.9%) distribution on the market which is why I'm going for it as well - https://developer.android.com/about/dashboards

Unfortunately, I won't have time to submit a PR for this. The build.gradle file is also a bit outdated so that will have to be fixed as well - had some issues when trying to run the sample app.

**Comment by szaboa** [comment]
Yes, I am aware of this number, however need to be considered how much extra effort you need to put in development vs what you will get from this 6.9%.

Worth to read it: https://www.thedroidsonroids.com/blog/forget-android-kitkat

Of course I will check what can I do to support 4.4 in the next couple of days. Will upgrade the dependencies at least for sure.
